---
# tasks file for roles/app
- name: Launch app
  docker_container:
    name: backend
    image: elenaortega/tp-devops:simple-api
    pull: yes
    networks:
      - name: app-network

    env:
      SPRING_DATASOURCE_PASSWORD: usr
      SPRING_DATASOURCE_USER: pwd
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
